### ISSUE TITLE
rest-api示例文档app.module.ts缺少errors.interceptor文件说明

### ISSUE THREAD

**Issue by zhangtanlin** [dzzzzzy/Nestjs-Learning#19]
参照Nestjs CRUD Restful API Demo示例，自己编写时，发现缺少Nestjs-Learning/demo/rest-api/src/common/下面errors.interceptor.ts和result.interface.ts两文件的说明，期望作者能够更新这两个文件说明。

**Comment by dzzzzzy** [comment]
已更新
