### ISSUE TITLE
rest-api示例文档app.module.ts使用typeorm连接数据库时，缺少ormconfig.json说明

### ISSUE THREAD

**Issue by zhangtanlin** [dzzzzzy/Nestjs-Learning#20]
示例文档app.module.ts里面这一行可能需要多添加一些备注，因为自己按照示例demo编写时，这里有点理解不清，
imports: [TypeOrmModule.forRoot(), CatModule],  // 导入其他模块的集合
可以备注一下，这里是结合ormconfig.json的typeorm配置的连接数据库的方法

**Comment by dzzzzzy** [comment]
已更新
