### ISSUE TITLE
嵌套的module应该怎么使用啊？

### ISSUE THREAD

**Issue by farzer** [dzzzzzy/Nestjs-Learning#23]
```
// Aservice
@Injectable
export class Aservice {}
```

```
// Acontroller
@Controller()
export class AController {
  constructor(private readonly aservice: AService) {} // 这里无法注入
}
```

```
// module A
@Module({
  controllers: [Acontroller],
  providers: [Aservice],
})
export class Amodule {}
```

```
// moduleB
@Module({
  imports: [Amodule],
})
export class Bmodule {}
```

```
// moduleC
@Module({
  imports: [Bmodule],
})
export class Cmodule {}
```

以上会报错

`Nest can't resolve dependencies of the AService (?). Please make sure that the argument at index [0] is available in the AModule context`

**Comment by farzer** [comment]
https://github.com/nestjs/nest/issues/2144

**Comment by dzzzzzy** [comment]
看了你的bug复现仓库，你的问题是出在 BService 的 构造函数中，nest 使用类的构造函数完成依赖注入，你在 BService 的构造函数传了 `options:any`，nest 在实例化 BService 的时候找不到这个 `options:any`，所以报错，如果你的想法是在类实例化时初始化 `options:any`，那让 BService 实现 `OnModuleInit` 这个接口，然后在实现方法中初始化 `options:any`

**Comment by farzer** [comment]
@dzzzzzy cool, thx
