### ISSUE TITLE
@nestjs/passport 抛出异常错误无法拦截的吗？

### ISSUE THREAD

**Issue by farzer** [dzzzzzy/Nestjs-Learning#24]
我看了一下 `handleRequest` 这个函数，如果没有认证会直接抛出错误

https://github.com/nestjs/passport/blob/master/lib/auth.guard.ts#L67

然后我设置了全局的拦截器，没有办法拦截

![image](https://user-images.githubusercontent.com/9881593/58146649-9c877e80-7c89-11e9-80e7-fa975adb43e0.png)

没有进入到 errorinspector 就直接返回了

**Comment by dzzzzzy** [comment]
这个阶段属于Guard中的处理逻辑，在Guard中抛出的异常是不会进入Interceptor的，可以使用Exception Filter来捕获这个异常

**Comment by farzer** [comment]
现在是这样处理，感觉这样会不会有逻辑是重复的啊？

**Comment by dzzzzzy** [comment]
推荐的做法是，拦截器里可以做日志拦截器，所有的异常捕获使用过滤器，这样就不会有逻辑重复

**Comment by farzer** [comment]
结果tranform返回也是过滤器吗？

**Comment by farzer** [comment]
嗯，在守卫文档的最后一句看到filter可以捕获guard的异常了
