### ISSUE TITLE
启动 unable connect database

### ISSUE THREAD

**Issue by nearxu** [dzzzzzy/Nestjs-Learning#26]
看了package 里面没有 mongo MySQL ，想问一下，这个数据库，是哪里的？

**Comment by dzzzzzy** [comment]
安装`mysql`依赖包，作为mysql连接驱动

**Comment by nearxu** [comment]
我现在连接数据库了，而且创建了表test ，但是还是报错，No repository for "User" was found. Looks like this entity is not registered in current "default" connection
