### ISSUE TITLE
希望添加一个 用户登陆的例子

### ISSUE THREAD

**Issue by SirM2z** [dzzzzzy/Nestjs-Learning#4]
看了官方的 auth 例子，看懂了，但还是不太知道怎么融入进项目里

另外，博主的文章写得很棒，我刚开始学 nest 框架，你关于 Module 的介绍那篇让明白不少东西，感谢

**Comment by dzzzzzy** [comment]
感谢反馈和夸奖～

我会在下一个demo中，使用 “用户” 和 “帖子” 这两个实体，介绍和实现 nest 中的登录、注册、用户授权/认证功能，顺便会介绍如何编写一个简单的基于 RBAC 的权限管理功能。敬请期待～

**Comment by SirM2z** [comment]
感谢博主更新，看到用户发帖的 demo了

目前有个疑问，这个 demo 的目录结构是这样的

&nbsp;.
 └── src
 　　　├── main.ts
 　　　├── app.module.ts
 　　　├── controllers
 　　　│　　　  ├── post.controller.ts
 　　　│　　　  └──user.controller.ts
 　　　└── services
 　　　 　　　├── post.services.ts
 　　　 　　　└──user.services.ts

我也看到很多 demo 目录结构是

&nbsp;.
 └── src
 　　　├── main.ts
 　　　├── app.module.ts
 　　　├── user
 　　　│　　├── user.services.ts
 　　　│　　└──user.controller.ts
 　　　└── post
 　　　 　　　├── post.services.ts
 　　　 　　　└── post.controller.ts

不知道有什么区别呢？  可能我之前看的 demo 都是比较简单的 :joy:

**Comment by dzzzzzy** [comment]
@SirM2z 用户登录例子已经完工 :tada:
