### ISSUE TITLE
老板讲讲nest cloud？

### ISSUE THREAD

**Issue by Muromi-Rikka** [dzzzzzy/Nestjs-Learning#40]

**Comment by dzzzzzy** [comment]
[nestcloud](https://github.com/nest-cloud/nestcloud) 是一个基于`nestjs`、 `consul`、`grpc` 的一个 nodejs 微服务框架，已经集成了服务治理、负载均衡、rpc调用、配置中心、分布式定时任务、api网关、日志，是目前nestjs生态圈中集成度和可用性比较高的微服务框架
