### ISSUE TITLE
Error: Cannot find module 'graphql/utilities/buildASTSchema'

### ISSUE THREAD

**Issue by tomoat** [dzzzzzy/Nestjs-Learning#6]
安装模块，运行rest-api，会出现错误： Error: Cannot find module 'graphql/utilities/buildASTSchema'

另外提一下，package.json缺失了@nestjs/graphql模块

**Comment by dzzzzzy** [comment]
@tomoat 非常感谢，这个问题是我在 rest-api demo 中多导入了 GraphQLModule，现在已经修复。
